name: C CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    defaults:
      run:
        working-directory: ./helloworld-c-app
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Build
      run: make all

    - name: Run Tests
      run: make test

    - name: Build Docker Image
      run: docker build -t hello-c-app .

    - name: Run Docker Container
      run: docker run hello-c-app
